version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wifi-troubleshooting-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - wifi-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wifi-troubleshooting-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - wifi-app-network

networks:
  wifi-app-network:
    driver: bridge

volumes:
  backend_data:
