[build]
  base = "."
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "frontend/dist"
