services:
  - type: web
    name: wifi-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: wifi-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: "nginx -g 'daemon off;'"
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: wifi-backend
          property: host
